services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: swe_project_db
      POSTGRES_USER: swe_user
      POSTGRES_PASSWORD: StrongPassword123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_web
    command: >
      sh -c "
      python - <<'PY'
import time, psycopg2
for i in range(30):
    try:
        psycopg2.connect(
            dbname='swe_project_db',
            user='swe_user',
            password='StrongPassword123!',
            host='db',
            port=5432
        ).close()
        print('DB is ready')
        break
    except Exception as e:
        print('Waiting for DB...', e)
        time.sleep(2)
else:
    raise SystemExit('DB not ready in time')
PY
      python swe_project/manage.py migrate --noinput &&
      python swe_project/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
      - media_data:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  media_data:
