version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: swe_project_db
      POSTGRES_USER: swe_user
      POSTGRES_PASSWORD: StrongPassword123!
    ports:
      - "8001:8001"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_web
    command: >
      sh -c "python swe_project/manage.py makemigrations &&
             python swe_project/manage.py migrate &&
             python swe_project/manage.py seed_db &&
             python swe_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - media_data:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  media_data:
