# Generated by Django 5.2.7 on 2025-10-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('supplierID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumerID', models.IntegerField()),
                ('supplierID', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('requestDate', models.DateField(auto_now_add=True)),
                ('consumerComment', models.TextField()),
            ],
        ),
    ]
